# Generated by Django 2.1.8 on 2019-04-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='Image Title', max_length=100),
        ),
    ]
