# Generated by Django 2.1.8 on 2019-04-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
