# Generated by Django 2.1.8 on 2019-04-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20190425_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
