# Generated by Django 2.1.8 on 2019-04-27 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_image_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_thumbnail',
        ),
    ]
